repos:
  - repo: local
    hooks:
      - id: mypy
        name: Validate types with MyPy
        entry: poetry run mypy
        language: system
        types: [python]

      - id: raff
        name: Format with ruff
        entry: poetry run ruff format
        language: system
        types: [python]

      - id: raff-check
        name: Check with ruff
        entry: poetry run ruff check
        language: system
        types: [python]
