name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: python -m pip install poetry
      - run: poetry install
      - run: poetry run ruff check
        env:
          FORCE_COLOR: 1
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: python -m pip install poetry
      - run: poetry install
      - run: poetry run mypy
        env:
          FORCE_COLOR: 1
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v2
      - name: Setup python${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"
      - run: python -m pip install poetry
      - run: poetry install
      - run: >-
          poetry run pytest \
            -vv \
            --cov-report=term-missing \
            --doctest-modules \
            tests
        env:
          FORCE_COLOR: 1
